### PR TITLE
Updated the UI landing page

### LINKED ISSUE #88: UI improvement
**Is your feature request related to a problem? Please describe.**
improve the UI look to make it better.

**Describe the solution you'd like**
Redesigning the UI.

### PR DESCRIPTION
**Pull request by frtug**
## What does this PR do?

updating the landing page with some font and animation 

## Issue

Fixes #88

## What changed?

- (background,font,animation)

## Why these changes?

This is an improvement 

## Is it tested?
Yes, attached down below

## Checklist

- [x] I have read through the [Contributing Guidelines](https://github.com/ambujraj/byteshare/blob/master/CONTRIBUTING.md)
- [x] I have also updated the dependent codes as well and README.md if applicable
- [x] My code adheres to consistent formatting standards and includes clear comments where necessary to enhance readability and understanding.

### CODE REVIEW

**Comment by frtug** [comment]
Screenshot 2024-04-10 at 16 04 45
Screenshot 2024-04-10 at 16 04 55

**Comment by frtug** [comment]
sorry, I had to force push this change coz there are some changed that i pushed which creates a conflit. There is nothing to worry now.

**Comment by frtug** [comment]
Hey @ambujraj,

Can you review my PR for Ui-improvement.?
Love to know what you think and how can I improve futher ?

**Comment by ambujraj** [comment]
Hi @frtug. Thanks for the update.
This looks much better. 
But please let me know if the below suggestions looks good:

- Background should be consistent in all pages where the current background is present
- Send button should be bouncing little lesser.
- Let's change the illustration on the left of home page to something similar to secure file sending
- Send button should be more focus gainer, either by making this larger or something else as you wish
- Decrease the line height of the text on the left to make it a paragraph of 3 lines, we will have to change the text also.
- The send button in mobile should be near to the user's thumb making them easier to click.

**Comment by ambujraj** [comment]
Hi @frtug. Thanks for the update. This looks much better. 

But please let me know if the below suggestion looks good:

- Background should be consistent in all pages where the current background is present
- Send button should be bouncing little lesser.
- Let's change the illustration on the left of home page to something similar to secure file sending
- Send button should be more focus gainer, either by making this larger or something else as you wish
- Decrease the line height of the text on the left to make it a paragraph of 3 lines, we will have to change the text also. (NEW TEXT - Experience seamless and secure file sharing with ByteShare. Send files effortlessly, keeping data safe and manageable.)
- The send button in mobile should be near to the user's thumb making them easier to click.

**Comment by frtug** [comment]
I was seeing 43 files changed here, so i didn't know what to do. 
I created a different PR #157 and addressed all the points we talked here.

**Pull request merged**
